embed_assets: on
package_assets: off
javascripts:
  vendor:
    - public/javascripts/vendor/jquery.js
    - public/javascripts/vendor/jquery.easing.js
    - public/javascripts/vendor/date.js
    - public/javascripts/vendor/polymaps.js
    - public/javascripts/vendor/protovis.js
    - public/javascripts/vendor/rails.js
    - public/javascripts/maptip.js
  app:
    - public/javascripts/lib/*.js
    - public/javascripts/*.js
    - public/javascripts/application.js
stylesheets:
  core:
    - public/stylesheets/reset.css
    - public/stylesheets/core.css
    - public/stylesheets/data.css
    - public/stylesheets/pictos.css
    - public/stylesheets/maptip.css
